services:
  devserve:
    image: node:lts-slim
    ports:
      - 3000:3000
    volumes:
      - ./:/app:Z
      - /app/.git
    working_dir: /app
    environment:
      - BROWSER=none
    command: npm start
