services:
  dev:
    build: .
    ports: [ 3000:3000 ]
    volumes:
      - ./.docusaurus:/app/.docusaurus
      - ./docs:/app/docs:ro
      - ./src:/app/src:ro
      - ./static:/app/static:ro
      - ./babel.config.js:/app/babel.config.js:ro
      - ./docusaurus.config.js:/app/docusaurus.config.js:ro
      - ./sidebars.js:/app/sidebars.js:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    tty: true
