/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  getstarted: [{ type: 'autogenerated', dirName: 'linux' }],
  browser: [{ type: 'autogenerated', dirName: 'browser' }],
  common: [{ type: 'autogenerated', dirName: 'common' }],
  dev: [{ type: 'autogenerated', dirName: 'dev' }],
  win: [{ type: 'autogenerated', dirName: 'win' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
